services:
  backend:
    build: ./backend
    ports:
      - "9000:9000"
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
